apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-backend
  template:
    metadata:
      labels:
        app: ai-backend
    spec:
      containers:
        - name: backend
          image: ankeshhkumar/ai-devops-assistant:dee386c54a3dbed8f480c9cf5a9dfe156e7ae5a3
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: DB_HOST
              value: postgres

            - name: DB_NAME
              value: ai_chat

            - name: DB_USER
              value: postgres

            - name: DB_PASSWORD
              value: postgres

            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openrouter-secret
                  key: OPENROUTER_API_KEY

            - name: OPENROUTER_MODEL
              value: "nvidia/nemotron-3-ultra-550b-a55b:free"

          # Liveness probe
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          # Readiness probe
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
