apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-postgres
  template:
    metadata:
      labels:
        app: ai-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: ai_chat
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
